# Generated by Django 2.2.28 on 2022-05-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='imagen',
            field=models.CharField(default='/none.jpg/', max_length=700),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(max_length=60),
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
