# Generated by Django 2.2.28 on 2022-05-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220512_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(height_field=100, upload_to='uploads/', width_field=100),
        ),
    ]
